assignment.zip : bildat_lab2_answers.pdf
	mkdir assignment; 
	cp bildat_lab2_answers.pdf ./assignment/bildat_lab2_answers.pdf;
	cp houghline.m ./assignment/houghline.m;
	cp houghedgeline.m ./assignment/houghedgeline.m;
	cp extractedge.m ./assignment/extractedge.m;
	cp Lv.m ./assignment/Lv.m;
	cp Lvvtilde.m ./assignment/Lvvtilde.m;
	cp Lvvvtilde.m ./assignment/Lvvvtilde.m;
	cp lab2.mlx ./assignment/lab2.mlx
	zip -r assignment.zip assignment;
	rm -r ./assignment; 
