assignment.zip : bildat_lab3_answers.pdf mixture_prob.m kmeans_segm.m lab3.mlx
	mkdir assignment; 
	cp bildat_lab3_answers.pdf ./assignment/bildat_lab3_answers.pdf;
	cp lab3.mlx ./assignment/lab3.mlx;
	cp mixture_prob.m ./assignment/mixture_prob.m;
	cp kmeans_segm.m ./assignment/kmeans_segm.m;
	zip -r assignment.zip assignment;
	rm -r ./assignment;


